sudo: false
language: rust
cache:
  cargo: true
rust:
  - stable
os:
  - linux
  - osx
before_install:
  - "export DISPLAY=:99.0"
addons:
  apt:
    packages:
      - libxxf86vm-dev
      - libosmesa6-dev
      - libcurl4-openssl-dev      # for kcov
      - libelf-dev                # for kcov
      - libdw-dev                 # for kcov
      - cmake
script:
  -  cargo test
