sudo: false
language: rust
cache:
  cargo: true
rust:
  - stable
os:
  - linux
  - osx
before_install:
  - "export DISPLAY=:99.0"
addons:
  apt:
    packages:
      - libxxf86vm-dev
      - libxinerama-dev
      - libxinerama1
      - libxcursor-dev
      - libxcursor1
      - libosmesa6-dev
script:
  -  cargo test
